
import java.util.HashMap;

public class MovesFactory {
    private static final HashMap<String, Moves> movesMap = new HashMap<String, Moves>();
    
    // list of all move
    static {
        movesMap.put("Pound", new Moves("Pound", 40));
        movesMap.put("Karate Chop", new Moves("Karate Chop", 50));
        movesMap.put("Double Slap", new Moves("Double Slap", 15));
        movesMap.put("Comet Punch", new Moves("Comet Punch", 18));
        movesMap.put("Mega Punch", new Moves("Mega Punch", 80));
        movesMap.put("Pay Day", new Moves("Pay Day", 40));
        movesMap.put("Fire Punch", new Moves("Fire Punch", 75));
        movesMap.put("Ice Punch", new Moves("Ice Punch", 75));
        movesMap.put("Thunder Punch", new Moves("Thunder Punch", 75));
        movesMap.put("Scratch", new Moves("Scratch", 40));
        movesMap.put("Vise Grip", new Moves("Vise Grip", 55));
        movesMap.put("Guillotine", new Moves("Guillotine", 0));
        movesMap.put("Razor Wind", new Moves("Razor Wind", 80));
        movesMap.put("Swords Dance", new Moves("Swords Dance", 0));
        movesMap.put("Cut", new Moves("Cut", 50));
        movesMap.put("Gust", new Moves("Gust", 40));
        movesMap.put("Wing Attack", new Moves("Wing Attack", 60));
        movesMap.put("Whirlwind", new Moves("Whirlwind", 0));
        movesMap.put("Fly", new Moves("Fly", 90));
        movesMap.put("Bind", new Moves("Bind", 15));
        movesMap.put("Slam", new Moves("Slam", 80));
        movesMap.put("Vine Whip", new Moves("Vine Whip", 45));
        movesMap.put("Stomp", new Moves("Stomp", 65));
        movesMap.put("Double Kick", new Moves("Double Kick", 30));
        movesMap.put("Mega Kick", new Moves("Mega Kick", 120));
        movesMap.put("Jump Kick", new Moves("Jump Kick", 100));
        movesMap.put("Rolling Kick", new Moves("Rolling Kick", 60));
        movesMap.put("Sand Attack", new Moves("Sand Attack", 0));
        movesMap.put("Headbutt", new Moves("Headbutt", 70));
        movesMap.put("Horn Attack", new Moves("Horn Attack", 65));
        movesMap.put("Fury Attack", new Moves("Fury Attack", 15));
        movesMap.put("Horn Drill", new Moves("Horn Drill", 0));
        movesMap.put("Tackle", new Moves("Tackle", 40));
        movesMap.put("Body Slam", new Moves("Body Slam", 85));
        movesMap.put("Wrap", new Moves("Wrap", 15));
        movesMap.put("Take Down", new Moves("Take Down", 90));
        movesMap.put("Thrash", new Moves("Thrash", 120));
        movesMap.put("Double-Edge", new Moves("Double-Edge", 120));
        movesMap.put("Tail Whip", new Moves("Tail Whip", 0));
        movesMap.put("Poison Sting", new Moves("Poison Sting", 15));
        movesMap.put("Twineedle", new Moves("Twineedle", 25));
        movesMap.put("Pin Missile", new Moves("Pin Missile", 25));
        movesMap.put("Leer", new Moves("Leer", 0));
        movesMap.put("Bite", new Moves("Bite", 60));
        movesMap.put("Growl", new Moves("Growl", 0));
        movesMap.put("Roar", new Moves("Roar", 0));
        movesMap.put("Sing", new Moves("Sing", 0));
        movesMap.put("Supersonic", new Moves("Supersonic", 0));
        movesMap.put("Sonic Boom", new Moves("Sonic Boom", 0));
        movesMap.put("Disable", new Moves("Disable", 0));
        movesMap.put("Acid", new Moves("Acid", 40));
        movesMap.put("Ember", new Moves("Ember", 40));
        movesMap.put("Flamethrower", new Moves("Flamethrower", 90));
        movesMap.put("Mist", new Moves("Mist", 0));
        movesMap.put("Water Gun", new Moves("Water Gun", 40));
        movesMap.put("Hydro Pump", new Moves("Hydro Pump", 110));
        movesMap.put("Surf", new Moves("Surf", 90));
        movesMap.put("Ice Beam", new Moves("Ice Beam", 90));
        movesMap.put("Blizzard", new Moves("Blizzard", 110));
        movesMap.put("Psybeam", new Moves("Psybeam", 65));
        movesMap.put("Bubble Beam", new Moves("Bubble Beam", 65));
        movesMap.put("Aurora Beam", new Moves("Aurora Beam", 65));
        movesMap.put("Hyper Beam", new Moves("Hyper Beam", 150));
        movesMap.put("Peck", new Moves("Peck", 35));
        movesMap.put("Drill Peck", new Moves("Drill Peck", 80));
        movesMap.put("Submission", new Moves("Submission", 80));
        movesMap.put("Low Kick", new Moves("Low Kick", 0));
        movesMap.put("Counter", new Moves("Counter", 0));
        movesMap.put("Seismic Toss", new Moves("Seismic Toss", 0));
        movesMap.put("Strength", new Moves("Strength", 80));
        movesMap.put("Absorb", new Moves("Absorb", 20));
        movesMap.put("Mega Drain", new Moves("Mega Drain", 40));
        movesMap.put("Leech Seed", new Moves("Leech Seed", 0));
        movesMap.put("Growth", new Moves("Growth", 0));
        movesMap.put("Razor Leaf", new Moves("Razor Leaf", 55));
        movesMap.put("Solar Beam", new Moves("Solar Beam", 120));
        movesMap.put("Poison Powder", new Moves("Poison Powder", 0));
        movesMap.put("Stun Spore", new Moves("Stun Spore", 0));
        movesMap.put("Sleep Powder", new Moves("Sleep Powder", 0));
        movesMap.put("Petal Dance", new Moves("Petal Dance", 120));
        movesMap.put("String Shot", new Moves("String Shot", 0));
        movesMap.put("Dragon Rage", new Moves("Dragon Rage", 0));
        movesMap.put("Fire Spin", new Moves("Fire Spin", 35));
        movesMap.put("Thunder Shock", new Moves("Thunder Shock", 40));
        movesMap.put("Thunderbolt", new Moves("Thunderbolt", 90));
        movesMap.put("Thunder Wave", new Moves("Thunder Wave", 0));
        movesMap.put("Thunder", new Moves("Thunder", 110));
        movesMap.put("Rock Throw", new Moves("Rock Throw", 50));
        movesMap.put("Earthquake", new Moves("Earthquake", 100));
        movesMap.put("Fissure", new Moves("Fissure", 0));
        movesMap.put("Dig", new Moves("Dig", 80));
        movesMap.put("Toxic", new Moves("Toxic", 0));
        movesMap.put("Confusion", new Moves("Confusion", 50));
        movesMap.put("Psychic", new Moves("Psychic", 90));
        movesMap.put("Hypnosis", new Moves("Hypnosis", 0));
        movesMap.put("Meditate", new Moves("Meditate", 0));
        movesMap.put("Agility", new Moves("Agility", 0));
        movesMap.put("Quick Attack", new Moves("Quick Attack", 40));
        movesMap.put("Rage", new Moves("Rage", 20));
        movesMap.put("Teleport", new Moves("Teleport", 0));
        movesMap.put("Night Shade", new Moves("Night Shade", 0));
        movesMap.put("Mimic", new Moves("Mimic", 0));
        movesMap.put("Screech", new Moves("Screech", 0));
        movesMap.put("Double Team", new Moves("Double Team", 0));
        movesMap.put("Recover", new Moves("Recover", 0));
        movesMap.put("Harden", new Moves("Harden", 0));
        movesMap.put("Minimize", new Moves("Minimize", 0));
        movesMap.put("Smokescreen", new Moves("Smokescreen", 0));
        movesMap.put("Confuse Ray", new Moves("Confuse Ray", 0));
        movesMap.put("Withdraw", new Moves("Withdraw", 0));
        movesMap.put("Defense Curl", new Moves("Defense Curl", 0));
        movesMap.put("Barrier", new Moves("Barrier", 0));
        movesMap.put("Light Screen", new Moves("Light Screen", 0));
        movesMap.put("Haze", new Moves("Haze", 0));
        movesMap.put("Reflect", new Moves("Reflect", 0));
        movesMap.put("Focus Energy", new Moves("Focus Energy", 0));
        movesMap.put("Bide", new Moves("Bide", 0));
        movesMap.put("Metronome", new Moves("Metronome", 0));
        movesMap.put("Mirror Move", new Moves("Mirror Move", 0));
        movesMap.put("Self-Destruct", new Moves("Self-Destruct", 200));
        movesMap.put("Egg Bomb", new Moves("Egg Bomb", 100));
        movesMap.put("Lick", new Moves("Lick", 30));
        movesMap.put("Smog", new Moves("Smog", 30));
        movesMap.put("Sludge", new Moves("Sludge", 65));
        movesMap.put("Bone Club", new Moves("Bone Club", 65));
        movesMap.put("Fire Blast", new Moves("Fire Blast", 110));
        movesMap.put("Waterfall", new Moves("Waterfall", 80));
        movesMap.put("Clamp", new Moves("Clamp", 35));
        movesMap.put("Swift", new Moves("Swift", 60));
        movesMap.put("Skull Bash", new Moves("Skull Bash", 130));
        movesMap.put("Spike Cannon", new Moves("Spike Cannon", 20));
        movesMap.put("Constrict", new Moves("Constrict", 10));
        movesMap.put("Amnesia", new Moves("Amnesia", 0));
        movesMap.put("Kinesis", new Moves("Kinesis", 0));
        movesMap.put("Soft-Boiled", new Moves("Soft-Boiled", 0));
        movesMap.put("High Jump Kick", new Moves("High Jump Kick", 130));
        movesMap.put("Glare", new Moves("Glare", 0));
        movesMap.put("Dream Eater", new Moves("Dream Eater", 100));
        movesMap.put("Poison Gas", new Moves("Poison Gas", 0));
        movesMap.put("Barrage", new Moves("Barrage", 15));
        movesMap.put("Leech Life", new Moves("Leech Life", 80));
        movesMap.put("Lovely Kiss", new Moves("Lovely Kiss", 0));
        movesMap.put("Sky Attack", new Moves("Sky Attack", 140));
        movesMap.put("Transform", new Moves("Transform", 0));
        movesMap.put("Bubble", new Moves("Bubble", 40));
        movesMap.put("Dizzy Punch", new Moves("Dizzy Punch", 70));
        movesMap.put("Spore", new Moves("Spore", 0));
        movesMap.put("Flash", new Moves("Flash", 0));
        movesMap.put("Psywave", new Moves("Psywave", 0));
        movesMap.put("Splash", new Moves("Splash", 0));
        movesMap.put("Acid Armor", new Moves("Acid Armor", 0));
        movesMap.put("Crabhammer", new Moves("Crabhammer", 100));
        movesMap.put("Explosion", new Moves("Explosion", 250));
        movesMap.put("Fury Swipes", new Moves("Fury Swipes", 18));
        movesMap.put("Bonemerang", new Moves("Bonemerang", 50));
        movesMap.put("Rest", new Moves("Rest", 0));
        movesMap.put("Rock Slide", new Moves("Rock Slide", 75));
        movesMap.put("Hyper Fang", new Moves("Hyper Fang", 80));
        movesMap.put("Sharpen", new Moves("Sharpen", 0));
        movesMap.put("Conversion", new Moves("Conversion", 0));
        movesMap.put("Tri Attack", new Moves("Tri Attack", 80));
        movesMap.put("Super Fang", new Moves("Super Fang", 0));
        movesMap.put("Slash", new Moves("Slash", 70));
        movesMap.put("Substitute", new Moves("Substitute", 0));
        movesMap.put("Struggle", new Moves("Struggle", 50));

    }
    
    public static Moves createMove(String moveName) {
        return movesMap.get(moveName);
    }
}
